# Generated by Django 6.0.3 on 2026-03-27 12:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContribuyenteICA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "nombre",
                    models.CharField(
                        max_length=300, verbose_name="Nombre/Razón Social"
                    ),
                ),
                ("nit", models.CharField(max_length=20, verbose_name="NIT")),
                (
                    "actividad",
                    models.CharField(
                        choices=[
                            ("101", "Industrial - Actividad Industrial"),
                            (
                                "201",
                                "Comercial - Alimentos, Víveres, Insumos Agrícolas",
                            ),
                            ("202", "Comercial - Equipos Computación, Venta Móvil"),
                            ("203", "Comercial - Lubricantes, Combustibles, Licores"),
                            ("204", "Comercial - Otras Actividades Comerciales"),
                            ("301", "Servicios - Construcción, Transporte, Telecom"),
                            ("302", "Servicios - Otras Actividades de Servicios"),
                            ("401", "Financiera"),
                        ],
                        max_length=3,
                        verbose_name="Actividad Económica",
                    ),
                ),
                (
                    "ingresos_brutos",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Ingresos Brutos Declarados ($)",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "impuesto_calculado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ingresos_proyectados",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribuyente ICA",
                "verbose_name_plural": "Contribuyentes ICA",
                "ordering": ["actividad", "-ingresos_brutos"],
            },
        ),
        migrations.CreateModel(
            name="ContribuyentePredial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "direccion",
                    models.CharField(
                        max_length=300, verbose_name="Dirección del Predio"
                    ),
                ),
                (
                    "nombre_predio",
                    models.CharField(max_length=200, verbose_name="Nombre del Predio"),
                ),
                (
                    "propietario",
                    models.CharField(max_length=300, verbose_name="Propietario"),
                ),
                (
                    "cedula_catastral",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Cédula Catastral"
                    ),
                ),
                (
                    "avaluo_catastral",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Avalúo Catastral ($)",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("UV", "Urbano - Vivienda"),
                            ("UEF", "Urbano Edificado - Act. Financieras"),
                            ("UED", "Urbano Edificado - Demás"),
                            ("UNEU", "Urbano No Edificado - Urbanizable No Urbanizado"),
                            ("UNUE", "Urbano No Edificado - Urbanizado No Edificado"),
                            ("UNNU", "Urbano No Edificado - No Urbanizable"),
                            ("RU", "Rural"),
                            ("PE", "Parcelación/Finca Recreo - Edificado"),
                            ("PNE", "Parcelación/Finca Recreo - No Edificado"),
                        ],
                        max_length=4,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "impuesto_calculado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribuyente Predial",
                "verbose_name_plural": "Contribuyentes Predial",
                "ordering": ["categoria", "-avaluo_catastral"],
            },
        ),
        migrations.CreateModel(
            name="ResumenCalculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(max_length=30, verbose_name="Tipo de Cálculo"),
                ),
                ("categoria", models.CharField(max_length=100)),
                ("descripcion_rango", models.CharField(blank=True, max_length=200)),
                (
                    "total_avaluo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tarifa_por_mil",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "recaudo_potencial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "cultura_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "proyeccion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("cantidad_predios", models.IntegerField(default=0)),
                ("fecha_calculo", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resumen de Cálculo",
                "verbose_name_plural": "Resúmenes de Cálculo",
                "ordering": ["tipo", "categoria"],
            },
        ),
        migrations.CreateModel(
            name="TarifaPredial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("UV", "Urbano - Vivienda"),
                            ("UEF", "Urbano Edificado - Act. Financieras"),
                            ("UED", "Urbano Edificado - Demás"),
                            ("UNEU", "Urbano No Edificado - Urbanizable No Urbanizado"),
                            ("UNUE", "Urbano No Edificado - Urbanizado No Edificado"),
                            ("UNNU", "Urbano No Edificado - No Urbanizable"),
                            ("RU", "Rural"),
                            ("PE", "Parcelación/Finca Recreo - Edificado"),
                            ("PNE", "Parcelación/Finca Recreo - No Edificado"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "uvt_desde",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rango inferior en UVT (dejar vacío si tarifa fija)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "uvt_hasta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rango superior en UVT (dejar vacío si sin límite)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tarifa_por_mil",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="Tarifa (x/1000)"
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Tarifa Predial",
                "verbose_name_plural": "Tarifas Predial",
                "ordering": ["vigencia", "categoria", "uvt_desde"],
            },
        ),
        migrations.CreateModel(
            name="CarteraVigenciaAnterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_calculo",
                    models.IntegerField(verbose_name="Vigencia de Cálculo"),
                ),
                (
                    "vigencia_cartera",
                    models.IntegerField(verbose_name="Año de la Cartera"),
                ),
                (
                    "valor_cartera",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="Valor Cartera ($)",
                    ),
                ),
                (
                    "porcentaje_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("40.00"),
                        max_digits=5,
                        verbose_name="% Base Recaudo",
                    ),
                ),
                (
                    "porcentaje_urbano",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        verbose_name="% Urbano",
                    ),
                ),
                (
                    "porcentaje_rural",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90.00"),
                        max_digits=5,
                        verbose_name="% Rural",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartera Vigencia Anterior",
                "verbose_name_plural": "Cartera Vigencias Anteriores",
                "ordering": ["-vigencia_cartera"],
                "unique_together": {("vigencia_calculo", "vigencia_cartera")},
            },
        ),
        migrations.CreateModel(
            name="CulturaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("UV", "Urbano - Vivienda"),
                            ("UEF", "Urbano Edificado - Act. Financieras"),
                            ("UED", "Urbano Edificado - Demás"),
                            ("UNEU", "Urbano No Edificado - Urbanizable No Urbanizado"),
                            ("UNUE", "Urbano No Edificado - Urbanizado No Edificado"),
                            ("UNNU", "Urbano No Edificado - No Urbanizable"),
                            ("RU", "Rural"),
                            ("PE", "Parcelación/Finca Recreo - Edificado"),
                            ("PNE", "Parcelación/Finca Recreo - No Edificado"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ej: 70.00 para 70%",
                        max_digits=5,
                        verbose_name="% Cultura de Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cultura de Pago",
                "verbose_name_plural": "Cultura de Pago",
                "unique_together": {("vigencia", "categoria")},
            },
        ),
        migrations.CreateModel(
            name="RubroIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "codigo",
                    models.CharField(max_length=50, verbose_name="Código Presupuestal"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=400, verbose_name="Descripción"),
                ),
                (
                    "codigo_fuente",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Cód. Fuente"
                    ),
                ),
                (
                    "nombre_fuente",
                    models.CharField(blank=True, max_length=100, verbose_name="Fuente"),
                ),
                (
                    "metodo_calculo",
                    models.CharField(
                        choices=[
                            ("PUVA", "Cálculo Predial Urbano Vig. Actual"),
                            ("PUAN", "Cálculo Predial Urbano Vig. Anteriores"),
                            ("PRVA", "Cálculo Predial Rural Vig. Actual"),
                            ("PRAN", "Cálculo Predial Rural Vig. Anteriores"),
                            ("ICAI", "Cálculo ICA Industrial"),
                            ("ICAC", "Cálculo ICA Comercial"),
                            ("ICAS", "Cálculo ICA Servicios"),
                            ("AT", "15% del Total ICA"),
                            ("IPC", "Incremento IPC sobre Recaudo Anterior"),
                            ("ICN", "Tasa Crecimiento ICN sobre Recaudo Anterior"),
                            ("POAI", "Tarifa % sobre POAI Inversión"),
                            ("MAN", "Valor Manual"),
                        ],
                        default="MAN",
                        max_length=4,
                    ),
                ),
                (
                    "recaudo_vigencia_anterior",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Recaudo Vig. Anterior ($)",
                    ),
                ),
                (
                    "tarifa_poai",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Ej: 0.025 para 2.5%",
                        max_digits=6,
                        null=True,
                        verbose_name="Tarifa POAI (%)",
                    ),
                ),
                (
                    "valor_apropiacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Valor Apropiación ($)",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "es_titulo",
                    models.BooleanField(
                        default=False, verbose_name="Es título/subtotal"
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "nivel",
                    models.IntegerField(
                        default=0, help_text="Nivel de jerarquía para indentación"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="ingresos.rubroingreso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro de Ingreso",
                "verbose_name_plural": "Rubros de Ingreso",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="TarifaICA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "codigo_actividad",
                    models.CharField(
                        choices=[
                            ("101", "Industrial - Actividad Industrial"),
                            (
                                "201",
                                "Comercial - Alimentos, Víveres, Insumos Agrícolas",
                            ),
                            ("202", "Comercial - Equipos Computación, Venta Móvil"),
                            ("203", "Comercial - Lubricantes, Combustibles, Licores"),
                            ("204", "Comercial - Otras Actividades Comerciales"),
                            ("301", "Servicios - Construcción, Transporte, Telecom"),
                            ("302", "Servicios - Otras Actividades de Servicios"),
                            ("401", "Financiera"),
                        ],
                        max_length=3,
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "tarifa_por_mil",
                    models.DecimalField(
                        decimal_places=3, max_digits=8, verbose_name="Tarifa (x/1000)"
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "Tarifa ICA",
                "verbose_name_plural": "Tarifas ICA",
                "unique_together": {("vigencia", "codigo_actividad")},
            },
        ),
    ]
