# Generated by Django 6.0.4 on 2026-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CifraHistoricaIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_calculo",
                    models.IntegerField(
                        help_text="Año para el cual se proyecta",
                        verbose_name="Vigencia de Cálculo",
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="Año Histórico")),
                (
                    "codigo_rubro",
                    models.CharField(max_length=50, verbose_name="Código Rubro"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=400, verbose_name="Descripción"),
                ),
                (
                    "valor_recaudo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Valor Recaudo ($)",
                    ),
                ),
                (
                    "es_icld",
                    models.BooleanField(
                        default=False,
                        help_text="Ingreso Corriente de Libre Destinación",
                        verbose_name="¿Es ICLD?",
                    ),
                ),
                ("es_sgp", models.BooleanField(default=False, verbose_name="¿Es SGP?")),
                (
                    "es_sgp_libre",
                    models.BooleanField(
                        default=False, verbose_name="¿Es SGP Libre Asignación?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cifra Histórica Ingreso",
                "verbose_name_plural": "Cifras Históricas Ingresos",
                "ordering": ["anio", "codigo_rubro"],
                "unique_together": {("vigencia_calculo", "anio", "codigo_rubro")},
            },
        ),
    ]
