# Generated by Django 6.0.4 on 2026-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0002_cifrahistoricaingreso"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="culturapago",
            options={
                "verbose_name": "Eficiencia Recaudo",
                "verbose_name_plural": "Eficiencia Recaudo",
            },
        ),
        migrations.AlterField(
            model_name="culturapago",
            name="porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Ej: 70.00 para 70%. Override por categoría; si no se define se usa el % global de Parámetros.",
                max_digits=5,
                verbose_name="% Eficiencia Recaudo",
            ),
        ),
    ]
