# Generated by Django 6.0.3 on 2026-04-24 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0003_alter_culturapago_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubroingreso",
            name="metodo_calculo",
            field=models.CharField(
                choices=[
                    ("PUVA", "Cálculo Predial Urbano Vig. Actual"),
                    ("PUAN", "Cálculo Predial Urbano Vig. Anteriores"),
                    ("PRVA", "Cálculo Predial Rural Vig. Actual"),
                    ("PRAN", "Cálculo Predial Rural Vig. Anteriores"),
                    ("ICAI", "Cálculo ICA Industrial"),
                    ("ICAC", "Cálculo ICA Comercial"),
                    ("ICAS", "Cálculo ICA Servicios"),
                    ("AT", "15% del Total ICA"),
                    ("IPC", "Incremento IPC sobre Recaudo Anterior"),
                    ("ICN", "Tasa Crecimiento ICN sobre Recaudo Anterior"),
                    ("POAI", "Tarifa % sobre POAI Inversión"),
                    ("EST", "Cálculo Estampilla (Base × Tarifa)"),
                    ("MAN", "Valor Manual"),
                ],
                default="MAN",
                max_length=4,
            ),
        ),
        migrations.CreateModel(
            name="Estampilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Adulto Mayor, Pro-cultura, Justicia Familiar",
                        max_length=120,
                        verbose_name="Nombre Estampilla",
                    ),
                ),
                (
                    "codigo_rubro",
                    models.CharField(
                        blank=True,
                        help_text="Opcional. Código al que se asocia la proyección",
                        max_length=50,
                        verbose_name="Código Rubro Presupuestal",
                    ),
                ),
                (
                    "tarifa",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ej: 0.02 = 2%. Se multiplica por la base de cálculo",
                        max_digits=6,
                        verbose_name="Tarifa",
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Estampilla",
                "verbose_name_plural": "Estampillas",
                "ordering": ["vigencia", "nombre"],
                "unique_together": {("vigencia", "nombre")},
            },
        ),
        migrations.AddField(
            model_name="rubroingreso",
            name="estampilla",
            field=models.ForeignKey(
                blank=True,
                help_text="Requerido cuando el método es Cálculo Estampilla",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingresos.estampilla",
                verbose_name="Estampilla asociada",
            ),
        ),
    ]
