# Generated by Django 6.0.4 on 2026-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingresos", "0004_alter_rubroingreso_metodo_calculo_estampilla_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estampilla",
            name="codigo_rubro_pensiones",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Rubro del Anexo 1 que recibe el 20% (ej: 1.3.6.1.1.01.02.300.55). Si se deja vacío se intenta automáticamente "1.3.6." + Código 80%.',
                max_length=50,
                verbose_name="Código Rubro 20% Fondo de Pensiones",
            ),
        ),
        migrations.AlterField(
            model_name="estampilla",
            name="codigo_rubro",
            field=models.CharField(
                blank=True,
                help_text="Rubro del Anexo 1 que recibe el 80% (ej: 1.1.01.02.300.55)",
                max_length=50,
                verbose_name="Código Rubro 80% Despacho/Secretarías",
            ),
        ),
    ]
