# Generated by Django 6.0.3 on 2026-03-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParametrosSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia",
                    models.IntegerField(unique=True, verbose_name="Vigencia Fiscal"),
                ),
                (
                    "valor_uvt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor UVT ($)"
                    ),
                ),
                (
                    "tasa_ipc",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ej: 0.051 para 5.1%",
                        max_digits=6,
                        verbose_name="Tasa IPC (%)",
                    ),
                ),
                (
                    "tasa_icn",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ej: 0.08 para 8%",
                        max_digits=6,
                        verbose_name="Tasa Crecimiento ICN (%)",
                    ),
                ),
                (
                    "tasa_pib_nominal",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ej: 0.062 para 6.2%",
                        max_digits=6,
                        verbose_name="Tasa PIB Nominal (%)",
                    ),
                ),
                (
                    "poai_total_inversion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="POAI Total Inversión (sin Educación, Vivienda, Salud)",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Parámetro del Sistema",
                "verbose_name_plural": "Parámetros del Sistema",
                "ordering": ["-vigencia"],
            },
        ),
    ]
