# Generated by Django 6.0.4 on 2026-04-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablaConcejoPersoneria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.IntegerField(
                        choices=[
                            (0, "Especial"),
                            (1, "Primera"),
                            (2, "Segunda"),
                            (3, "Tercera"),
                            (4, "Cuarta"),
                            (5, "Quinta"),
                            (6, "Sexta"),
                        ],
                        unique=True,
                        verbose_name="Categoría Municipio",
                    ),
                ),
                (
                    "honorario_concejal_smlmv",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Honorario Concejal (factor SMLMV)",
                    ),
                ),
                (
                    "sesiones_ordinarias",
                    models.IntegerField(
                        default=70, verbose_name="Sesiones Ordinarias/Año"
                    ),
                ),
                (
                    "sesiones_extraordinarias",
                    models.IntegerField(
                        default=12, verbose_name="Sesiones Extraordinarias/Año"
                    ),
                ),
                (
                    "num_concejales",
                    models.IntegerField(
                        default=11, verbose_name="Número de Concejales"
                    ),
                ),
                (
                    "limite_concejo_pct_icld",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Límite Concejo (% ICLD)",
                    ),
                ),
                (
                    "limite_personeria_pct_icld",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Límite Personería (% ICLD)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabla Concejo/Personería",
                "verbose_name_plural": "Tablas Concejo/Personería",
                "ordering": ["categoria"],
            },
        ),
        migrations.CreateModel(
            name="VigenciaFutura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(verbose_name="Vigencia de Registro")),
                (
                    "vigencia_futura",
                    models.IntegerField(verbose_name="Año de la Vigencia Futura"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=500, verbose_name="Descripción / Objeto"
                    ),
                ),
                (
                    "codigo_fuente",
                    models.CharField(max_length=20, verbose_name="Código Fuente"),
                ),
                (
                    "nombre_fuente",
                    models.CharField(max_length=200, verbose_name="Nombre Fuente"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Valor ($)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("APR", "Aprobada"), ("EJE", "En Ejecución")],
                        default="APR",
                        max_length=3,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Vigencia Futura",
                "verbose_name_plural": "Vigencias Futuras",
                "ordering": ["vigencia_futura", "codigo_fuente"],
            },
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="categoria_municipio",
            field=models.IntegerField(
                default=6,
                help_text="1-6 o 0 para Especial",
                verbose_name="Categoría del Municipio",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_promedio_pagos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Para cálculo estampillas",
                max_digits=6,
                verbose_name="% Promedio Pagos/Aprob. Definitiva",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="tcpa_gastos",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Tasa Compuesta Promedio Anual de gastos últimos 4 años",
                max_digits=8,
                verbose_name="TCPA Gastos (%)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="tcpa_ingresos",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Tasa Compuesta Promedio Anual de ingresos últimos 4 años",
                max_digits=8,
                verbose_name="TCPA Ingresos (%)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="valor_smlmv",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Valor SMLMV ($)",
            ),
        ),
    ]
