# Generated by Django 6.0.4 on 2026-04-18 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tablaconcejopersoneria_vigenciafutura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_crecimiento_viviendas",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0.015"),
                help_text="Incremento anual de viviendas para proyección predial urbano vivienda. Ej: 0.015 = 1.5%",
                max_digits=8,
                verbose_name="% Crecimiento Viviendas",
            ),
        ),
    ]
