# Generated by Django 6.0.4 on 2026-04-18 15:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_pct_crecimiento_viviendas"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_cartera_base",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("40.00"),
                help_text="Porcentaje base de recaudo sobre el valor de cartera de vigencias anteriores. Ej: 40.00 = 40%",
                max_digits=5,
                verbose_name="% Base Recaudo Cartera",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_cartera_rural",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("90.00"),
                help_text="Porción de la cartera asignada a predial rural. Ej: 90.00 = 90%",
                max_digits=5,
                verbose_name="% Rural Cartera",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_cartera_urbano",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Porción de la cartera asignada a predial urbano. Ej: 10.00 = 10%",
                max_digits=5,
                verbose_name="% Urbano Cartera",
            ),
        ),
    ]
