# Generated by Django 6.0.4 on 2026-04-18 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_pct_cartera_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_eficiencia_recaudo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("70.00"),
                help_text="Porcentaje global de eficiencia de recaudo (antes Cultura de Pago). Se aplica al recaudo potencial. Ej: 70.00 = 70%",
                max_digits=5,
                verbose_name="% Eficiencia Recaudo",
            ),
        ),
    ]
