# Generated by Django 6.0.3 on 2026-04-24 21:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_parametrossistema_pct_eficiencia_recaudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrossistema",
            name="cuentas_por_pagar_nc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="Cuentas por Pagar NC ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="gasto_sev_ppto_nc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Gasto apropiado en Salud, Educación y Vivienda sobre presupuesto NC",
                max_digits=20,
                verbose_name="Gasto SEV Ppto NC ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="gasto_sev_sgr",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Gasto apropiado en Salud, Educación y Vivienda sobre SGR",
                max_digits=20,
                verbose_name="Gasto SEV SGR ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_pagos_sgr",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.3480"),
                help_text="Ej: 0.3480 = 34.80%. Promedio ppto últimas 3 vigencias SGR",
                max_digits=6,
                verbose_name="% Promedio Pagos SGR",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_pagos_sin_sgr",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.8483"),
                help_text="Ej: 0.8483 = 84.83%. Promedio ppto últimas 3 vigencias sin SGR",
                max_digits=6,
                verbose_name="% Promedio Pagos sin SGR",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="reservas_presupuestales_nc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="Reservas Presupuestales NC ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="sgr_presupuesto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="Presupuesto SGR ($)",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="superavit_fiscal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name="Superávit Fiscal Estimado ($)",
            ),
        ),
    ]
