# Generated by Django 6.0.3 on 2026-04-27 19:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_parametrossistema_cuentas_por_pagar_nc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_pagos_despacho",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.8000"),
                help_text="Peso del componente de despacho/secretarías sobre el % promedio pagos. Ej: 0.80 = 80%",
                max_digits=6,
                verbose_name="% Pagos Despacho y Secretarías",
            ),
        ),
        migrations.AddField(
            model_name="parametrossistema",
            name="pct_pagos_pensiones",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.2000"),
                help_text="Peso del componente Fondo de Pensiones sobre el % promedio pagos. Ej: 0.20 = 20%",
                max_digits=6,
                verbose_name="% Pagos Fondo de Pensiones",
            ),
        ),
    ]
