# Generated by Django 4.2.30 on 2026-07-01 14:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bsp_y_prima_servicios_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrossistema',
            name='pct_aporte_arl',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00522'), help_text='Decreto 1295/1994. Varía por clase de riesgo. Default 0.522% (clase I)', max_digits=6, verbose_name='% Aporte ARL'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='pct_incremento_pensionados',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.040'), help_text='Ley 100/1993 art. 14: incremento igual al IPC del año anterior.', max_digits=6, verbose_name='% Incremento Mesada Pensionados'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='pct_incremento_salarial',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.081'), help_text='Decreto salarial anual del Gobierno. Ej: 0.081 = 8.1% (proy 2027)', max_digits=6, verbose_name='% Incremento Salarial Anual'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='pct_limite_funcionamiento_ley617',
            field=models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='% máximo sobre ICLD. Categorías: Esp=50, 1=55, 2-3=60, 4-5=75, 6=80', max_digits=6, verbose_name='% Límite Gastos Funcionamiento (Ley 617)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='subsidio_transporte_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('274000'), help_text='Aplica a empleados con sueldo ≤ 2 SMLMV. Decreto SMLMV anual.', max_digits=12, verbose_name='Subsidio Transporte Mensual ($)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='tcr_deuda',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.921'), help_text='Factor multiplicador de intereses para cubrir riesgo. Default 0.921', max_digits=6, verbose_name='Tasa Cobertura Riesgo (TCR)'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='umbral_smlmv_bsp',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Si salario_mensual ≤ umbral × SMLMV → BSP bajo; sino BSP alto. Dto 1042/78.', max_digits=4, verbose_name='Umbral SMLMV para BSP'),
        ),
        migrations.CreateModel(
            name='TechoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.IntegerField(verbose_name='Vigencia Fiscal')),
                ('orden', models.IntegerField(default=0)),
                ('concepto_ingreso', models.CharField(max_length=200, verbose_name='Concepto de Ingreso / Fuente')),
                ('codigo_fuente', models.CharField(blank=True, max_length=20)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rendimientos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fto', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Funcionamiento')),
                ('deuda', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vf', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Vigencias Futuras')),
                ('vivienda', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('medio_ambiente', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Techo de Inversion',
                'verbose_name_plural': 'Techos de Inversion',
                'ordering': ['vigencia', 'orden', 'concepto_ingreso'],
                'unique_together': {('vigencia', 'concepto_ingreso')},
            },
        ),
    ]
