# Generated by Django 6.0.7 on 2026-07-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mfmp_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteFinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Fuente')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fuente de Financiación',
                'verbose_name_plural': 'Fuentes de Financiación',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ley617Proyectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('gastos_funcionamiento', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('icld_neto', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('pct_limite', models.DecimalField(decimal_places=2, default=80, help_text='% límite legal Ley 617 según categoría (5-6=80%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Ley 617 Proyectado',
                'verbose_name_plural': 'Ley 617 Proyectados',
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='IngresoCorrienteLey358',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ccpet', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=300)),
                ('fuente', models.CharField(max_length=10)),
                ('ejec_2024', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('ejec_2025', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('aforo_2026', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('aplica_ley_358', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ingreso Corriente Ley 358',
                'verbose_name_plural': 'Ingresos Corrientes Ley 358',
                'ordering': ['codigo_ccpet'],
                'unique_together': {('codigo_ccpet', 'fuente')},
            },
        ),
        migrations.CreateModel(
            name='PlanFinancieroLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'A. INGRESOS TOTALES'), ('B', 'B. FUNCIONAMIENTO'), ('B1', 'B.1 Personal'), ('B2', 'B.2 Bienes, Servicios y Otros'), ('C', 'C. SERVICIO DE LA DEUDA'), ('D', 'D. INVERSIÓN'), ('T', 'Total Gastos (B+C+D)')], max_length=3)),
                ('anio', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
            ],
            options={
                'verbose_name': 'Plan Financiero',
                'verbose_name_plural': 'Plan Financiero',
                'ordering': ['tipo', 'anio'],
                'unique_together': {('tipo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='POAIPorDependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=200)),
                ('pct_participacion', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('anio', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
            ],
            options={
                'verbose_name': 'POAI por Dependencia',
                'verbose_name_plural': 'POAI por Dependencias',
                'ordering': ['-valor'],
                'unique_together': {('dependencia', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='CuadrePorFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadres', to='core.fuentefinanciacion')),
            ],
            options={
                'verbose_name': 'Cuadre por Fuente',
                'verbose_name_plural': 'Cuadres por Fuente',
                'ordering': ['fuente', 'anio'],
                'unique_together': {('fuente', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='ICLDProyectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('ley_99', models.DecimalField(decimal_places=2, default=0, help_text='1% Ley 99/1993 (CAR)', max_digits=22)),
                ('fonpet', models.DecimalField(decimal_places=2, default=0, help_text='Contingente FONPET', max_digits=22)),
                ('otros_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icld_proyectado', to='core.fuentefinanciacion')),
            ],
            options={
                'verbose_name': 'ICLD Proyectado',
                'verbose_name_plural': 'ICLD Proyectados',
                'ordering': ['fuente', 'anio'],
                'unique_together': {('fuente', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='POAIProyectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poai_proyectado', to='core.fuentefinanciacion')),
            ],
            options={
                'verbose_name': 'POAI Proyectado',
                'verbose_name_plural': 'POAI Proyectados',
                'ordering': ['fuente', 'anio'],
                'unique_together': {('fuente', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='SaldoVFPorFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_referencia', models.IntegerField()),
                ('apropiacion_definitiva', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('cdp_vigentes', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('vf_aprobadas', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('vf_en_tramite', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('vf_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vf_saldos', to='core.fuentefinanciacion')),
            ],
            options={
                'verbose_name': 'Saldo VF por Fuente',
                'verbose_name_plural': 'Saldos VF por Fuente',
                'ordering': ['fuente'],
                'unique_together': {('fuente', 'anio_referencia')},
            },
        ),
    ]
