# Generated by Django 6.0.7 on 2026-07-12 16:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fuentefinanciacion_ley617proyectado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refinanciacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicar', models.BooleanField(default=False, verbose_name='Aplicar Refinanciación')),
                ('anio_refinanciacion', models.IntegerField(default=2029, verbose_name='Año de Refinanciación')),
                ('nueva_tasa_ea', models.DecimalField(decimal_places=4, default=Decimal('0.11'), max_digits=6, verbose_name='Nueva Tasa E.A.')),
                ('nuevo_plazo_anios', models.IntegerField(default=8, verbose_name='Nuevo Plazo Total (años)')),
                ('anios_gracia', models.IntegerField(default=1, verbose_name='Años de Gracia')),
                ('saldo_refinanciar', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('pagare_objetivo', models.CharField(default='Pagaré 1 - BBVA', max_length=100)),
            ],
            options={
                'verbose_name': 'Refinanciación',
                'verbose_name_plural': 'Refinanciaciones',
            },
        ),
        migrations.CreateModel(
            name='RefinanciacionProyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('saldo_original', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('intereses', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('amortizacion', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
            ],
            options={
                'verbose_name': 'Refinanciación (proyección)',
                'verbose_name_plural': 'Refinanciación (proyecciones)',
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='CCPETGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro_presupuestal', models.CharField(max_length=40, verbose_name='Rubro Presupuestal')),
                ('fuente', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('vigencia', models.IntegerField(default=2027)),
            ],
            options={
                'verbose_name': 'CCPET Gasto',
                'verbose_name_plural': 'CCPET Gastos',
                'ordering': ['rubro_presupuestal'],
                'unique_together': {('vigencia', 'rubro_presupuestal', 'fuente')},
            },
        ),
        migrations.CreateModel(
            name='CCPETIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro_presupuestal', models.CharField(max_length=40, verbose_name='Rubro Presupuestal')),
                ('fuente', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('vigencia', models.IntegerField(default=2027)),
            ],
            options={
                'verbose_name': 'CCPET Ingreso',
                'verbose_name_plural': 'CCPET Ingresos',
                'ordering': ['rubro_presupuestal'],
                'unique_together': {('vigencia', 'rubro_presupuestal', 'fuente')},
            },
        ),
    ]
