# Generated by Django 6.0.7 on 2026-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_baseestampillasanual_cargapoaiproyecto_icoproyeccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VigenciaFuturaAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('acto_aprobacion', models.CharField(max_length=200, verbose_name='Acto de Aprobación (Acuerdo/Ordenanza)')),
                ('objeto_proyecto', models.TextField(verbose_name='Objeto / Proyecto')),
                ('nombre_fuente', models.CharField(max_length=200, verbose_name='Fuente de Financiación')),
                ('codigo_fuente', models.CharField(blank=True, max_length=20)),
                ('val_2026', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2027', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2028', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2029', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2030', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2031', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2032', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2033', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2034', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2035', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('val_2036', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
            ],
            options={
                'verbose_name': 'Vigencia Futura Aprobada',
                'verbose_name_plural': 'Vigencias Futuras Aprobadas',
                'ordering': ['numero'],
            },
        ),
    ]
