# Generated by Django 6.0.7 on 2026-07-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vigenciafuturaaprobada'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionMensualIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('codigo_ccpet', models.CharField(max_length=40, verbose_name='Código CCPET')),
                ('codigo_fuente', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('apropiacion_definitiva', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('ene', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('abr', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('ago', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('dic', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
            ],
            options={
                'verbose_name': 'Ejecución Mensual Ingreso',
                'verbose_name_plural': 'Ejecución Mensual Ingresos',
                'ordering': ['anio', 'codigo_ccpet'],
                'unique_together': {('anio', 'codigo_ccpet', 'codigo_fuente')},
            },
        ),
    ]
