# Generated by Django 6.0.7 on 2026-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ejecucionmensualingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrossistema',
            name='poblacion_dane',
            field=models.IntegerField(default=0, help_text='Población proyectada DANE para la vigencia', verbose_name='Población DANE'),
        ),
    ]
