"""Constantes globales del sistema SIPRE."""

BANCOS_COLOMBIA = [
    'Banco Agrario de Colombia',
    'Banco AV Villas',
    'Banco BBVA Colombia',
    'Banco Caja Social',
    'Banco Cooperativo Coopcentral',
    'Banco Credifinanciera',
    'Banco Davivienda',
    'Banco de Bogotá',
    'Banco de Occidente',
    'Banco Falabella',
    'Banco GNB Sudameris',
    'Banco Itaú',
    'Banco Pichincha',
    'Banco Popular',
    'Banco Santander de Negocios Colombia',
    'Banco Serfinanza',
    'Banco W',
    'Bancóldex',
    'Bancolombia',
    'Bancoomeva',
    'Bancamía',
    'Banco Mundo Mujer',
    'BTG Pactual',
    'Citibank Colombia',
    'FDN - Financiera de Desarrollo Nacional',
    'Findeter',
    'FONADE - Enterritorio',
    'IDEA - Instituto para el Desarrollo de Antioquia',
    'INFIS - Institutos Financieros Estatales',
    'JP Morgan Colombia',
    'Scotiabank Colpatria',
]
