# Generated by Django 4.2.25 on 2026-04-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuenteFinanciacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "codigo",
                    models.CharField(max_length=20, verbose_name="Código Fuente"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre Fuente"),
                ),
            ],
            options={
                "verbose_name": "Fuente de Financiación",
                "verbose_name_plural": "Fuentes de Financiación",
                "ordering": ["codigo"],
                "unique_together": {("vigencia", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="SeccionGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "codigo",
                    models.CharField(max_length=10, verbose_name="Código Sección"),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre Sección"),
                ),
            ],
            options={
                "verbose_name": "Sección Presupuestal",
                "verbose_name_plural": "Secciones Presupuestales",
                "ordering": ["codigo"],
                "unique_together": {("vigencia", "codigo")},
            },
        ),
        migrations.CreateModel(
            name="RubroGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField()),
                (
                    "codigo",
                    models.CharField(
                        max_length=80, verbose_name="Identificación Presupuestal"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "codigo_fuente",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Cód. Fuente"
                    ),
                ),
                (
                    "nombre_fuente",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nombre Fuente"
                    ),
                ),
                (
                    "tipo_gasto",
                    models.CharField(
                        choices=[
                            ("FUN", "Funcionamiento"),
                            ("INV", "Inversión"),
                            ("DEU", "Servicio de la Deuda"),
                        ],
                        default="FUN",
                        max_length=3,
                        verbose_name="Tipo de Gasto",
                    ),
                ),
                (
                    "valor_apropiacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Apropiación ($)",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "es_titulo",
                    models.BooleanField(
                        default=False, verbose_name="Es título/subtotal"
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                (
                    "nivel",
                    models.IntegerField(
                        default=0, help_text="Nivel de jerarquía para indentación"
                    ),
                ),
                (
                    "fuente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gastos.fuentefinanciacion",
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hijos",
                        to="gastos.rubrogasto",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gastos.secciongasto",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubro de Gasto",
                "verbose_name_plural": "Rubros de Gasto",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="EjecucionGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "presupuesto_aprobado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Presupuesto Aprobado",
                    ),
                ),
                (
                    "adiciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Adiciones",
                    ),
                ),
                (
                    "reducciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Reducciones",
                    ),
                ),
                (
                    "traslado_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Traslado Crédito",
                    ),
                ),
                (
                    "traslado_contra_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Traslado Contra Crédito",
                    ),
                ),
                (
                    "aplazamientos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Aplazamientos",
                    ),
                ),
                (
                    "desaplazamientos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Desaplazamientos",
                    ),
                ),
                (
                    "cdp",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=20, verbose_name="CDP"
                    ),
                ),
                (
                    "compromisos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Compromisos",
                    ),
                ),
                (
                    "ordenado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Obligaciones (Ordenado)",
                    ),
                ),
                (
                    "pagado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Pagado",
                    ),
                ),
                (
                    "rubro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejecucion",
                        to="gastos.rubrogasto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de Gasto",
                "verbose_name_plural": "Ejecución de Gastos",
            },
        ),
    ]
