# Generated by Django 6.0.4 on 2026-04-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicioDeuda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(verbose_name="Vigencia")),
                (
                    "entidad_financiera",
                    models.CharField(max_length=200, verbose_name="Entidad Financiera"),
                ),
                (
                    "objeto_credito",
                    models.CharField(max_length=500, verbose_name="Objeto del Crédito"),
                ),
                (
                    "valor_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Valor Inicial del Crédito ($)",
                    ),
                ),
                (
                    "saldo_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Saldo Capital ($)",
                    ),
                ),
                (
                    "tasa_interes",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Ej: 0.12 para 12%",
                        max_digits=6,
                        verbose_name="Tasa Interés (%)",
                    ),
                ),
                (
                    "plazo_meses",
                    models.IntegerField(default=0, verbose_name="Plazo Total (meses)"),
                ),
                (
                    "meses_restantes",
                    models.IntegerField(default=0, verbose_name="Meses Restantes"),
                ),
                (
                    "cuota_capital_anual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Cuota Capital Anual ($)",
                    ),
                ),
                (
                    "intereses_anual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Intereses Anuales ($)",
                    ),
                ),
                (
                    "codigo_fuente",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código Fuente"
                    ),
                ),
                (
                    "nombre_fuente",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fuente Financiación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de Deuda",
                "verbose_name_plural": "Servicios de Deuda",
                "ordering": ["entidad_financiera"],
            },
        ),
        migrations.CreateModel(
            name="CifraHistoricaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_calculo",
                    models.IntegerField(verbose_name="Vigencia de Cálculo"),
                ),
                ("anio", models.IntegerField(verbose_name="Año Histórico")),
                (
                    "codigo_rubro",
                    models.CharField(max_length=80, verbose_name="Código Rubro"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "valor_apropiacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Apropiación Definitiva ($)",
                    ),
                ),
                (
                    "valor_compromisos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Compromisos ($)",
                    ),
                ),
                (
                    "valor_pagos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Pagos ($)",
                    ),
                ),
                (
                    "tipo_gasto",
                    models.CharField(
                        choices=[
                            ("FUN", "Funcionamiento"),
                            ("INV", "Inversión"),
                            ("DEU", "Servicio de la Deuda"),
                        ],
                        default="FUN",
                        max_length=3,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cifra Histórica Gasto",
                "verbose_name_plural": "Cifras Históricas Gastos",
                "ordering": ["anio", "codigo_rubro"],
                "unique_together": {("vigencia_calculo", "anio", "codigo_rubro")},
            },
        ),
        migrations.CreateModel(
            name="CostoPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(verbose_name="Vigencia")),
                ("cargo", models.CharField(max_length=200, verbose_name="Cargo")),
                (
                    "grado",
                    models.CharField(blank=True, max_length=20, verbose_name="Grado"),
                ),
                ("cantidad", models.IntegerField(default=1, verbose_name="Cantidad")),
                (
                    "salario_basico",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Salario Básico Mensual ($)",
                    ),
                ),
                (
                    "prima_navidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prima de Navidad ($)",
                    ),
                ),
                (
                    "prima_vacaciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prima de Vacaciones ($)",
                    ),
                ),
                (
                    "prima_servicios",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prima de Servicios ($)",
                    ),
                ),
                (
                    "cesantias",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Cesantías ($)",
                    ),
                ),
                (
                    "intereses_cesantias",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Intereses Cesantías ($)",
                    ),
                ),
                (
                    "vacaciones",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Vacaciones ($)",
                    ),
                ),
                (
                    "aportes_salud",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Aportes Salud ($)",
                    ),
                ),
                (
                    "aportes_pension",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Aportes Pensión ($)",
                    ),
                ),
                (
                    "aportes_arl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Aportes ARL ($)",
                    ),
                ),
                (
                    "aportes_caja",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Aportes Caja ($)",
                    ),
                ),
                (
                    "aportes_icbf",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Aportes ICBF ($)",
                    ),
                ),
                (
                    "aportes_sena",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Aportes SENA ($)",
                    ),
                ),
                (
                    "es_pensionado",
                    models.BooleanField(default=False, verbose_name="¿Es pensionado?"),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gastos.secciongasto",
                        verbose_name="Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costo de Personal",
                "verbose_name_plural": "Costos de Personal",
                "ordering": ["seccion", "cargo"],
            },
        ),
    ]
