# Generated by Django 6.0.4 on 2026-04-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0002_serviciodeuda_cifrahistoricagasto_costopersonal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia", models.IntegerField(verbose_name="Vigencia de Registro")),
                (
                    "banco",
                    models.CharField(
                        max_length=200, verbose_name="Entidad Financiera / Banco"
                    ),
                ),
                (
                    "renta_pignorada",
                    models.CharField(
                        help_text="Ej: ITO (Impuesto Transporte Oleoductos)",
                        max_length=200,
                        verbose_name="Renta Pignorada",
                    ),
                ),
                (
                    "objeto_credito",
                    models.CharField(max_length=500, verbose_name="Objeto del Crédito"),
                ),
                (
                    "valor_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Valor Total del Contrato ($)",
                    ),
                ),
                (
                    "plazo_meses",
                    models.IntegerField(default=0, verbose_name="Plazo Total (meses)"),
                ),
                (
                    "codigo_fuente",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código Fuente"
                    ),
                ),
                (
                    "nombre_fuente",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fuente Financiación"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contrato de Crédito",
                "verbose_name_plural": "Contratos de Crédito",
                "ordering": ["banco"],
            },
        ),
        migrations.AlterModelOptions(
            name="serviciodeuda",
            options={
                "verbose_name": "Servicio de Deuda (Legacy)",
                "verbose_name_plural": "Servicios de Deuda (Legacy)",
            },
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="codigo_fuente",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="cuota_capital_anual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="intereses_anual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="meses_restantes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="nombre_fuente",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="plazo_meses",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="saldo_capital",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="tasa_interes",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="serviciodeuda",
            name="valor_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name="PagareCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pagare",
                    models.CharField(max_length=50, verbose_name="Número de Pagaré"),
                ),
                (
                    "fecha_desembolso",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Desembolso"
                    ),
                ),
                (
                    "valor_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Valor Capital del Pagaré ($)",
                    ),
                ),
                (
                    "tasa_ibr",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="IBR de la semana de firma del pagaré",
                        max_digits=8,
                        verbose_name="Tasa IBR (%)",
                    ),
                ),
                (
                    "puntos",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Determinados en el contrato con el banco",
                        max_digits=8,
                        verbose_name="Puntos Adicionales (%)",
                    ),
                ),
                (
                    "tasa_cobertura_riesgo",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Cambia trimestralmente según Superfinanciera",
                        max_digits=8,
                        verbose_name="Tasa Cobertura Riesgo - TCR (%)",
                    ),
                ),
                (
                    "plazo_meses",
                    models.IntegerField(
                        default=0, verbose_name="Plazo del Pagaré (meses)"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagares",
                        to="gastos.contratocredito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagaré de Crédito",
                "verbose_name_plural": "Pagarés de Crédito",
                "ordering": ["contrato", "numero_pagare"],
            },
        ),
        migrations.CreateModel(
            name="AmortizacionPagare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vigencia_pago", models.IntegerField(verbose_name="Vigencia de Pago")),
                (
                    "capital_principal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Capital (Principal) ($)",
                    ),
                ),
                (
                    "intereses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Intereses sin TCR ($)",
                    ),
                ),
                (
                    "intereses_tcr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Intereses TCR ($)",
                    ),
                ),
                (
                    "pagare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amortizaciones",
                        to="gastos.pagarecredito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amortización de Pagaré",
                "verbose_name_plural": "Amortizaciones de Pagaré",
                "ordering": ["vigencia_pago"],
                "unique_together": {("pagare", "vigencia_pago")},
            },
        ),
    ]
