# Generated by Django 6.0.3 on 2026-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gastos", "0003_contratocredito_alter_serviciodeuda_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubrogasto",
            name="metodo_calculo",
            field=models.CharField(
                choices=[
                    ("MAN", "Manual"),
                    ("DCAP", "Servicio Deuda - Capital (vigencia)"),
                    ("DINT", "Servicio Deuda - Intereses (vigencia)"),
                    ("DTOT", "Servicio Deuda - Total (Capital + Intereses + TCR)"),
                    ("PEN", "Costo total Pensionados (Fondo de Pensiones)"),
                    ("CPS", "Costo Personal por Sección (rubro = sección.cargo)"),
                ],
                default="MAN",
                max_length=4,
                verbose_name="Método de Cálculo",
            ),
        ),
    ]
